language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 10.17.0

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add lerna
  - yarn global add codecov -W
  - lerna bootstrap
script:
  - yarn build:tsPackage
  - yarn test
  - codecov -f coverage/*.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
