language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10.17.0

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - lerna bootstrap
script:
  - yarn add codecov -g -W
  - yarn build
  - yarn test
  - codecov -f coverage/*.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
