language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 10.17.0
install:
  - yarn global add codecov -W
  - yarn
script:
  - yarn build
  - yarn test
  - codecov -f coverage/*.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
