language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10.17.0
install:
  - yarn
script:
  - yarn add codecov -g -W
  - yarn test
  - codecov -f coverage/*.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
